spring:
  application:
    name: eureka-provider
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://tlh:123456@localhost:8081/eureka/
  instance:
    appname: eureka-provider