spring:
  application:
    name: user-service
  zipkin:
    base-url: zipkin-server
    discovery-client-enabled: true
server:
  port: 8082
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
#      defaultZone: http://tlh:123456@localhost:8081/eureka/
      defaultZone: http://localhost:8089/eureka/
  instance:
    appname: eureka-provider
    hostname: tlh-user
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5 # 发送给注册中心的心跳频率
    lease-expiration-duration-in-seconds: 5 # 心跳间隔的超时时间，如果没有收到则移除该instance
    prefer-ip-address: true # 使用IP地址注册