server:
  port: 10032
scca:
  rest:
    context-path: /xhr
  ui:
    rest-server-context-path: /xhr
    rest-server-url: http://localhost:10032
spring:
  datasource:
    url: jdbc:mysql:///config_server
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: tlh-config-admin-db
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8089/eureka/
    healthcheck:
      enabled: true
  instance:
    appname: tlh-config-admin-db
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
    metadata-map: # 设置spring boot admin 的认证信息
      user.name: tlh
      user.password: 123456