server:
  port: 8095
spring:
  application:
    name: tlh-transaction-substitution
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8089/eureka/
  instance:
    appname: tlh-transaction-substitution
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
feign:
  hystrix:
    enabled: true # 开启hystrix支持
