server:
  port: 8096
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8089/eureka/
    healthcheck:
      enabled: true
  instance:
    appname: tlh-gateway
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
spring:
  application:
    name: tlh-gateway
  cloud:
    gateway:
      routes:
        - id: requestratelimiter_route
          uri: http://localhost:8096/sms/send   # todo 没有生效
          predicates:
            - Method=GET
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10  # 每秒允许的请求数
                redis-rate-limiter.burstCapacity: 20  # 桶的大小
                key-resolver: "#{@remoteAddKeyResolver}"