server:
  port: 8084
spring:
  application:
    name: consume-feign
eureka:
  instance:
    appname: consume-feign
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://tlh:123456@localhost:8081/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  compression: # 开启GZIP压缩
    request:
      enabled: true
    response:
      enabled: true