server:
  port: 8097
  servlet:
    path: /exam
spring:
  application:
    name: tlh-service-exam
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8089/eureka/
    healthcheck:
      enabled: true
  instance:
    appname: tlh-service-exam
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
tlh:
  rate:
    basePackage: org.tlh.springcloud.controller