server:
  port: 8090
spring:
  application:
    name: scc-config-client
eureka:
  instance:
    appname: scc-config-client
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8089/eureka/