spring:
  application:
    name: eureka-comsumer
server:
  port: 8083
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://tlh:123456@localhost:8081/eureka/
  instance:
    appname: eureka-comsumer
    hostname: tlh-consume
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5 # 发送给注册中心的心跳频率
    lease-expiration-duration-in-seconds: 5 # 心跳间隔的超时时间，如果没有收到则移除该instance
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream # 开启stream 的web接口
