server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql:///config_server
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: 123456
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
  profiles:
    active: jdbc # 激活config-DB方式
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT `KEY`, `VALUE` from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?
          order: 0