server:
  port: 10032
scca:
  rest:
    context-path: /xhr
  ui:
    rest-server-context-path: /xhr
    rest-server-url: http://localhost:10032
  git:
    repo-uri: file://Volumes/文档/学习/spring-cloud-learn/config-repo
spring:
  datasource:
    url: jdbc:mysql:///config_server
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
security:
  user:
    name: username